backend/crm/urls.py
from django.urls import path
from .views import dashboard_view, support_view, users_list_view, users_detail_view, foods_list_view, foods_detail_view, \
    categories_list_view, categories_detail_view, settings_view, settings_theme_view, food_delete_view, \
    category_delete_view, tips_list_view, tips_detail_view, tips_delete_view, extras_list_view, extras_delete_view, \
    extras_detail_view, orders_list_view, orders_detail_view, orders_create_view, orders_update_view
from .api import UserSeatsView

app_name = 'crm'

urlpatterns = [
    path('dashboard/', dashboard_view, name='dashboard'),
    path('dashboard/users/', users_list_view, name='users_list'),
    path('dashboard/users/<int:pk>/', users_detail_view, name='users_detail'),
    path('dashboard/orders/', orders_list_view, name='orders_list'),
    path('dashboard/orders/create/', orders_create_view, name='orders_create'),
    path('dashboard/orders/<int:pk>/update/', orders_update_view, name='orders_update'),
    path('dashboard/orders/<int:pk>/', orders_detail_view, name='orders_detail'),
    path('dashboard/foods/', foods_list_view, name='foods_list'),
    path('dashboard/foods/<int:pk>/', foods_detail_view, name='foods_detail'),
    path('dashboard/foods/delete/', food_delete_view, name='foods_delete'),
    path('dashboard/categories/', categories_list_view, name='categories_list'),
    path('dashboard/categories/<int:pk>/', categories_detail_view, name='categories_detail'),
    path('dashboard/categories/delete/', category_delete_view, name='categories_delete'),
    path('dashboard/tips/', tips_list_view, name='tips_list'),
    path('dashboard/tips/<int:pk>/', tips_detail_view, name='tips_detail'),
    path('dashboard/tips/delete/', tips_delete_view, name='tips_delete'),
    path('dashboard/extras/', extras_list_view, name='extras_list'),
    path('dashboard/extras/<int:pk>/', extras_detail_view, name='extras_detail'),
    path('dashboard/extras/delete/', extras_delete_view, name='extras_delete'),
    path('dashboard/settings/', settings_view, name='dashboard_settings'),
    path('dashboard/settings/theme/', settings_theme_view, name='dashboard_settings_theme'),
    path('dashboard/support/<int:pk>/', support_view, name='dashboard_support'),
    path("api/crm/seats/", UserSeatsView.as_view(), name="seats_list"),
]

backend/crm/models.py
from django.db import models

# Create your models here.

backend/crm/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from account.utils import is_manager_user
from stream.models import UserRoom
from main.models import Food, Category
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from core.utils import fancy_message
from .forms import UserForm, SeatFormSet, FoodForm, CategoryForm, ThemeForm, SettingForm, CustomUserCreationForm, \
    TipForm, ExtraForm, OrderForm, OrderItemFormSet
from settings.models import Theme, Setting
from django.db import transaction
from django.views.decorators.http import require_POST
from checkout.models import Extra, Tip, Order, OrderItem


# Create your views here.

@login_required
@user_passes_test(is_manager_user)
def dashboard_view(request, *args, **kwargs):
    my_context = {
        "Title": "Dashboard"
    }

    return render(request, "crm/dashboard.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def users_list_view(request, *args, **kwargs):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            fancy_message(request, "User successfully created!", "success")
            return redirect(".")
        else:
            fancy_message(request, form.errors, "error")

    queryset = get_user_model().objects.all()

    page = request.GET.get('page')

    items_per_page = 10
    paginator = Paginator(queryset, items_per_page)

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    form = CustomUserCreationForm()
    my_context = {
        "Title": "Account List",
        "users": users,
        "page": page,
        "form": form,
    }

    return render(request, "crm/users/users_list.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def users_detail_view(request, pk, *args, **kwargs):
    user = get_object_or_404(get_user_model(), id=pk)
    form = UserForm(instance=user)
    formset = SeatFormSet(instance=user)
    if request.method == "POST":
        print(request.POST)
        form = UserForm(instance=user, data=request.POST)
        formset = SeatFormSet(instance=user, data=request.POST)
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            fancy_message(request, "Changes saved successfully", level="success")
            return redirect(".")
        else:
            fancy_message(request, form.errors, level="error")
            fancy_message(request, formset.errors, level="error")

    my_context = {
        "Title": user.username,
        "form": form,
        "formset": formset
    }
    return render(request, "crm/users/users_detail.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def orders_list_view(request, *args, **kwargs):
    if request.method == "POST":
        form = OrderForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            fancy_message(request, "Order successfully created!", "success")
            return redirect(".")
        else:
            fancy_message(request, form.errors, "error")
    queryset = Order.objects.all()

    items_per_page = 10

    paginator = Paginator(queryset, items_per_page)

    page = request.GET.get('page')

    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
        orders = paginator.page(1)
    except EmptyPage:
        orders = paginator.page(paginator.num_pages)

    form = OrderForm()

    my_context = {
        "Title": "Order List",
        "orders": orders,
        "page": page,
        "form": form
    }

    return render(request, "crm/orders/orders_list.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def orders_detail_view(request, pk, *args, **kwargs):
    order = get_object_or_404(Order, id=pk)
    my_context = {
        "Title": order.id,
        "order": order,
    }
    return render(request, "crm/orders/orders_detail.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def orders_update_view(request, pk, *args, **kwargs):
    order = get_object_or_404(Order, id=pk)
    form = OrderForm(instance=order)
    formset = OrderItemFormSet(instance=order)
    if request.method == "POST":
        form = OrderForm(instance=order, data=request.POST, files=request.FILES)
        formset = OrderItemFormSet(instance=order, data=request.POST, files=request.FILES)
        if form.is_valid() and formset.is_valid():
            form_obj = form.save()
            formset.save()
            fancy_message(request, "Changes saved successfully", level="success")
            return redirect("crm:orders_detail", pk=form_obj.id)
        else:
            fancy_message(request, form.errors, level="error")
            fancy_message(request, formset.errors, level="error")

    my_context = {
        "Title": "Create Order",
        "form": form,
        "formset": formset
    }
    return render(request, "crm/orders/orders_create.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def orders_create_view(request, *args, **kwargs):
    form = OrderForm()
    formset = OrderItemFormSet()
    if request.method == "POST":
        form = OrderForm(data=request.POST, files=request.FILES)
        formset = OrderItemFormSet(data=request.POST, files=request.FILES)

        if form.is_valid() and formset.is_valid():
            form_obj = form.save()
            formset_obj = formset.save(commit=False)

            for index, item in enumerate(formset_obj):
                item.order = form_obj
                item.save()

                seats = request.POST.getlist(f'order_items-{index}-seats')
                item.seats.set(seats)

            fancy_message(request, "Order successfully created", level="success")
            return redirect("crm:orders_detail", pk=form_obj.id)
        else:
            fancy_message(request, form.errors, level="error")
            fancy_message(request, formset.errors, level="error")

    my_context = {
        "Title": "Create Order",
        "form": form,
        "formset": formset
    }
    return render(request, "crm/orders/orders_create.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def foods_list_view(request, *args, **kwargs):
    if request.method == "POST":
        form = FoodForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            fancy_message(request, "Food successfully created!", "success")
            return redirect(".")
        else:
            fancy_message(request, form.errors, "error")
    queryset = Food.objects.all()

    items_per_page = 10

    paginator = Paginator(queryset, items_per_page)

    page = request.GET.get('page')

    try:
        foods = paginator.page(page)
    except PageNotAnInteger:
        foods = paginator.page(1)
    except EmptyPage:
        foods = paginator.page(paginator.num_pages)

    form = FoodForm()

    my_context = {
        "Title": "Food List",
        "foods": foods,
        "page": page,
        "form": form
    }

    return render(request, "crm/foods/foods_list.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def foods_detail_view(request, pk, *args, **kwargs):
    food = get_object_or_404(Food, id=pk)
    form = FoodForm(instance=food)
    if request.method == "POST":
        form = FoodForm(instance=food, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            fancy_message(request, "Changes saved successfully", level="success")
            return redirect(".")
        else:
            fancy_message(request, form.errors, level="error")

    my_context = {
        "Title": food.name,
        "form": form,
    }
    return render(request, "crm/foods/foods_detail.html", my_context)


@require_POST
@login_required
@user_passes_test(is_manager_user)
def food_delete_view(request, *args, **kwargs):
    id = request.POST.get("food-id")
    food = get_object_or_404(Food, id=id)
    food.delete()
    fancy_message(request, "Food Deleted", level="success")
    return redirect("crm:foods_list")


@login_required
@user_passes_test(is_manager_user)
def categories_list_view(request, *args, **kwargs):
    if request.method == "POST":
        form = CategoryForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            fancy_message(request, "Food successfully created!", "success")
            return redirect(".")
        else:
            fancy_message(request, form.errors, "error")

    queryset = Category.objects.all()

    items_per_page = 10

    paginator = Paginator(queryset, items_per_page)

    page = request.GET.get('page')

    try:
        categories = paginator.page(page)
    except PageNotAnInteger:
        categories = paginator.page(1)
    except EmptyPage:
        categories = paginator.page(paginator.num_pages)

    form = CategoryForm()

    my_context = {
        "Title": "category List",
        "categories": categories,
        "page": page,
        "form": form,
    }

    return render(request, "crm/categories/categories_list.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def categories_detail_view(request, pk, *args, **kwargs):
    category = get_object_or_404(Category, id=pk)
    form = CategoryForm(instance=category)
    if request.method == "POST":
        form = CategoryForm(instance=category, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            fancy_message(request, "Changes saved successfully", level="success")
            return redirect(".")
        else:

backend/settings/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.

backend/templates/crm/settings/settings.html
{% extends 'index.html' %}
{% block content %}

    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item mx-1" role="presentation">
            <button class="nav-link active" id="pills-general-tab" data-bs-toggle="pill" data-bs-target="#pills-general"
                    type="button" role="tab" aria-controls="pills-general" aria-selected="true">General
            </button>
        </li>
        <li class="nav-item mx-1" role="presentation">
            <button class="nav-link " id="pills-theme-tab" data-bs-toggle="pill" data-bs-target="#pills-theme"
                    type="button" role="tab" aria-controls="pills-theme" aria-selected="false">Theme
            </button>
        </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active " id="pills-general" role="tabpanel" aria-labelledby="pills-general-tab"
             tabindex="0">
            <section>
                <form enctype="multipart/form-data" action="." method="post">
                    {% csrf_token %}
                    <div class="card bg-white shadow-sm border-0">
                        <div class="card-body">
                            <div class="row row-gap-2">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label class="form-label"
                                               for="{{ setting_form.company_name.name }}">{{ setting_form.company_name.label }}</label>
                                        {{ setting_form.company_name }}
                                        <small class="text-black-50">{{ setting_form.company_name.help_text }}</small>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label class="form-label"
                                               for="{{ setting_form.logo.name }}">{{ setting_form.logo.label }}</label>
                                        {{ setting_form.logo }}
                                        <small class="text-black-50">{{ setting_form.logo.help_text }}</small>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label class="form-label"
                                               for="{{ setting_form.logo_mini.name }}">{{ setting_form.logo_mini.label }}</label>
                                        {{ setting_form.logo_mini }}
                                        <small class="text-black-50">{{ setting_form.logo_mini.help_text }}</small>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label class="form-label"
                                               for="{{ setting_form.payment_gateways.name }}">{{ setting_form.payment_gateways.label }}</label>
                                        {{ setting_form.payment_gateways }}
                                        <small class="text-black-50">{{ setting_form.payment_gateways.help_text }}</small>
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-dark my-2 float-end" style="width: fit-content" role="button"
                                    type="submit">
                                Save
                            </button>
                        </div>
                    </div>
                </form>
            </section>
        </div>
        <div class="tab-pane fade " id="pills-theme" role="tabpanel" aria-labelledby="pills-theme-tab"
             tabindex="0">
            <form method="post" action="{% url "crm:dashboard_settings_theme" %}" enctype="multipart/form-data">
                {% csrf_token %}
                <section class="card bg-white border-0 shadow-sm">
                    <div class="card-body">
                        <input type="hidden" id="theme-input" name="theme"
                               value="{% if primary_theme %}{{ primary_theme.id }}{% else %}0{% endif %}">
                        <div class="row">
                            <div class="col-12 col-md-4 col-xl-3">
                                <div class="card bg-white shadow-sm">
                                    <div class="card-header bg-transparent">
                                        <h3 class="card-title">Themes</h3>
                                    </div>
                                    <div class="card-body d-flex justify-content-center align-items-center">
                                        {% include 'crm/settings/template.html' %}
                                    </div>
                                    <div class="card-footer bg-white">
                                        <div class="d-flex justify-content-start align-items-start flex-wrap gap-2">
                                            {% for theme in themes %}
                                                <div class="themes rounded-circle {% if theme.is_primary %}active{% endif %}"
                                                     data-id="{{ theme.id }}"
                                                     style="background-color: {{ theme.primary_color }};color:{{ theme.primary_color }} "></div>
                                            {% endfor %}
                                            <div class="vr"></div>
                                            <div class="themes rounded-circle {% if not primary_theme %}active{% endif %}"
                                                 data-id="0"
                                                 style="background-color: #ff6e00;color:#ff6e00 "></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-8 col-xl-9">
                                <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 row-gap-2 " id="theme-forms">
                                    {% for form in theme_form %}
                                        <div class="col">
                                            <div class="form-group">
                                                <label class="form-label" for="{{ form.name }}">{{ form.label }}</label>
                                                {{ form }}
                                                <small class="text-black-50">{{ form.help_text }}</small>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-dark my-2 float-end" style="width: fit-content" role="button"
                                type="submit">
                            Save
                        </button>
                    </div>
                </section>
            </form>
        </div>
    </div>


{% endblock %}
{% block script %}
    <script>

        const THEME_ITEMS = [
            {
                id: 0,
                primary_color: "#ff6e00",
                secondary_color: "#a088ef",
                light_color: "#F8F9FA",
                body_bg_color: "#f5f5f5",
                name: "Default",
                success_color: "#4CAF50",
                info_color: "#2196F3",
                warning_color: "#FFC107",
                danger_color: "#D7385E",
                dark_color: "#2E384D",
            },
            {% for theme in themes %}
                {
                    id: {{ theme.id }},
                    name: "{{ theme.name }}",
                    primary_color: "{{ theme.primary_color }}",
                    secondary_color: "{{ theme.secondary_color }}",
                    success_color: "{{ theme.success_color }}",
                    info_color: "{{ theme.info_color }}",
                    warning_color: "{{ theme.warning_color }}",
                    danger_color: "{{ theme.danger_color }}",
                    light_color: "{{ theme.light_color }}",
                    dark_color: "{{ theme.dark_color }}",
                    body_bg_color: "{{ theme.body_bg_color }}",
                },
            {% endfor %}
        ]

        const themeItems = document.querySelectorAll(".themes")

        const primary = "{{ primary_theme }}"

        if (primary === "None") {
            document.querySelectorAll("#theme-forms input[type=text]").forEach(form => {
                const name = form.getAttribute("name")
                form.value = THEME_ITEMS[0][name]
                form.disabled = THEME_ITEMS[0].id === 0;
            })
        }

        themeItems.forEach(item => {
            item.addEventListener("click", (e) => {
                const id = parseInt(e.currentTarget.getAttribute("data-id"))
                const templateName = document.querySelector("#template #name")
                const templateCart = document.querySelector("#template #cart")
                const templateBG = document.querySelector("#template #background")
                const templateSidebar = document.querySelector("#template #sidebar")
                const templateSidebarItems = document.querySelectorAll("#template [id^=sidebar_item-]")
                const templateOrderItems = document.querySelectorAll("#template [id^=order-]")

                const selectedTheme = THEME_ITEMS.filter(theme => theme.id === id)[0]
                templateCart.setAttribute("fill", selectedTheme.primary_color)
                templateSidebarItems.forEach(item => item.setAttribute("fill", selectedTheme.primary_color))
                templateOrderItems.forEach(item => item.setAttribute("fill", selectedTheme.secondary_color))
                templateName.setAttribute("fill", selectedTheme.secondary_color)
                templateSidebar.setAttribute("fill", selectedTheme.light_color)
                templateBG.setAttribute("fill", selectedTheme.body_bg_color)

                document.querySelector(".themes.active").classList.remove("active")
                e.currentTarget.classList.add("active")
                document.querySelector("#theme-input").value = id


                document.querySelectorAll("#theme-forms input[type=text]").forEach(form => {
                    const name = form.getAttribute("name")
                    form.value = selectedTheme[name]
                    form.disabled = selectedTheme.id === 0;
                })


            })
        })


    </script>
{% endblock %}

backend/templates/crm/settings/template.html
<svg width="323" height="184" viewBox="0 0 323 184" fill="none" xmlns="http://www.w3.org/2000/svg">
    <g id="template">
        <rect id="background" x="0.5" y="0.5" width="321.814" height="183" fill="#F5F5F5" stroke="#D2D2D2"/>
        <rect id="sidebar" x="1" y="1" width="34.4463" height="182" fill="#F8F9FA"/>
        <rect id="name" x="46.7571" y="11.2825" width="55.0113" height="14.9096" rx="3" fill="#A088EF"/>
        <rect id="cart" x="295.593" y="11.2825" width="14.9096" height="14.9096" rx="4" fill="#FF8B4C"/>
        <g id="menu">
            <g id="Group 2" filter="url(#filter0_d_2_59)">
                <rect id="Rectangle 5" x="46.7571" y="49.8418" width="83.2143" height="89.9717" rx="4" fill="#F8F9FA"/>
                <path id="Rectangle 6"
                      d="M46.7571 53.8418C46.7571 51.6327 48.5479 49.8418 50.7571 49.8418H125.971C128.18 49.8418 129.971 51.6327 129.971 53.8418V112.963H46.7571V53.8418Z"
                      fill="#B6AFAF"/>
                <rect id="order-3" x="97.28" y="128.037" width="27.2428" height="7.5369" rx="2" fill="#A088EF"/>
            </g>
            <g id="Group 3" filter="url(#filter1_d_2_59)">
                <rect id="Rectangle 5_2" x="136.901" y="49.8418" width="83.2143" height="89.9717" rx="4"
                      fill="#F8F9FA"/>
                <path id="Rectangle 6_2"
                      d="M136.901 53.8418C136.901 51.6327 138.692 49.8418 140.901 49.8418H216.115C218.324 49.8418 220.115 51.6327 220.115 53.8418V112.963H136.901V53.8418Z"
                      fill="#B6AFAF"/>
                <rect id="order-2" x="187.424" y="128.037" width="27.2428" height="7.5369" rx="2" fill="#A088EF"/>
            </g>
            <g id="Group 4" filter="url(#filter2_d_2_59)">
                <rect id="Rectangle 5_3" x="227.045" y="49.8418" width="83.2143" height="89.9717" rx="4"
                      fill="#F8F9FA"/>
                <path id="Rectangle 6_3"
                      d="M227.045 53.8418C227.045 51.6327 228.836 49.8418 231.045 49.8418H306.259C308.468 49.8418 310.259 51.6327 310.259 53.8418V112.963H227.045V53.8418Z"
                      fill="#B6AFAF"/>
                <rect id="order-1" x="277.568" y="128.037" width="27.2428" height="7.5369" rx="2" fill="#A088EF"/>
            </g>
        </g>
        <g id="sidebar-items">
            <rect id="sidebar_item-3" x="10.7684" y="34.9322" width="14.9096" height="14.9096" rx="4" fill="#FF8B4C"/>
            <rect id="sidebar_item-2" x="10.7684" y="58.5819" width="14.9096" height="14.9096" rx="4" fill="#FF8B4C"/>
            <rect id="sidebar_item-1" x="10.7684" y="82.2316" width="14.9096" height="14.9096" rx="4" fill="#FF8B4C"/>
        </g>
    </g>
    <defs>
        <filter id="filter0_d_2_59" x="38.7571" y="45.8418" width="99.2143" height="105.972"
                filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
            <feFlood flood-opacity="0" result="BackgroundImageFix"/>
            <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
                           result="hardAlpha"/>
            <feOffset dy="4"/>
            <feGaussianBlur stdDeviation="4"/>
            <feComposite in2="hardAlpha" operator="out"/>
            <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
            <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2_59"/>
            <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2_59" result="shape"/>
        </filter>
        <filter id="filter1_d_2_59" x="128.901" y="45.8418" width="99.2143" height="105.972"
                filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
            <feFlood flood-opacity="0" result="BackgroundImageFix"/>
            <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
                           result="hardAlpha"/>
            <feOffset dy="4"/>
            <feGaussianBlur stdDeviation="4"/>
            <feComposite in2="hardAlpha" operator="out"/>
            <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
            <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2_59"/>
            <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2_59" result="shape"/>
        </filter>
        <filter id="filter2_d_2_59" x="219.045" y="45.8418" width="99.2143" height="105.972"
                filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
            <feFlood flood-opacity="0" result="BackgroundImageFix"/>
            <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
                           result="hardAlpha"/>
            <feOffset dy="4"/>
            <feGaussianBlur stdDeviation="4"/>
            <feComposite in2="hardAlpha" operator="out"/>
            <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
            <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2_59"/>
            <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2_59" result="shape"/>
        </filter>
    </defs>
</svg>