backend/crm/urls.py
from django.urls import path
from .views import dashboard_view, support_view, users_list_view, users_detail_view, foods_list_view, foods_detail_view, \
    categories_list_view, categories_detail_view, settings_view, settings_theme_view, food_delete_view, \
    category_delete_view, tips_list_view, tips_detail_view, tips_delete_view, extras_list_view, extras_delete_view, \
    extras_detail_view, orders_list_view, orders_detail_view, orders_create_view, orders_update_view
from .api import UserSeatsView

app_name = 'crm'

urlpatterns = [
    path('dashboard/', dashboard_view, name='dashboard'),
    path('dashboard/users/', users_list_view, name='users_list'),
    path('dashboard/users/<int:pk>/', users_detail_view, name='users_detail'),
    path('dashboard/orders/', orders_list_view, name='orders_list'),
    path('dashboard/orders/create/', orders_create_view, name='orders_create'),
    path('dashboard/orders/<int:pk>/update/', orders_update_view, name='orders_update'),
    path('dashboard/orders/<int:pk>/', orders_detail_view, name='orders_detail'),
    path('dashboard/foods/', foods_list_view, name='foods_list'),
    path('dashboard/foods/<int:pk>/', foods_detail_view, name='foods_detail'),
    path('dashboard/foods/delete/', food_delete_view, name='foods_delete'),
    path('dashboard/categories/', categories_list_view, name='categories_list'),
    path('dashboard/categories/<int:pk>/', categories_detail_view, name='categories_detail'),
    path('dashboard/categories/delete/', category_delete_view, name='categories_delete'),
    path('dashboard/tips/', tips_list_view, name='tips_list'),
    path('dashboard/tips/<int:pk>/', tips_detail_view, name='tips_detail'),
    path('dashboard/tips/delete/', tips_delete_view, name='tips_delete'),
    path('dashboard/extras/', extras_list_view, name='extras_list'),
    path('dashboard/extras/<int:pk>/', extras_detail_view, name='extras_detail'),
    path('dashboard/extras/delete/', extras_delete_view, name='extras_delete'),
    path('dashboard/settings/', settings_view, name='dashboard_settings'),
    path('dashboard/settings/theme/', settings_theme_view, name='dashboard_settings_theme'),
    path('dashboard/support/<int:pk>/', support_view, name='dashboard_support'),
    path("api/crm/seats/", UserSeatsView.as_view(), name="seats_list"),
]

backend/crm/models.py
from django.db import models

# Create your models here.

backend/crm/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from account.utils import is_manager_user
from stream.models import UserRoom
from main.models import Food, Category
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from core.utils import fancy_message
from .forms import UserForm, SeatFormSet, FoodForm, CategoryForm, ThemeForm, SettingForm, CustomUserCreationForm, \
    TipForm, ExtraForm, OrderForm, OrderItemFormSet
from settings.models import Theme, Setting
from django.db import transaction
from django.views.decorators.http import require_POST
from checkout.models import Extra, Tip, Order, OrderItem


# Create your views here.

@login_required
@user_passes_test(is_manager_user)
def dashboard_view(request, *args, **kwargs):
    my_context = {
        "Title": "Dashboard"
    }

    return render(request, "crm/dashboard.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def users_list_view(request, *args, **kwargs):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            fancy_message(request, "User successfully created!", "success")
            return redirect(".")
        else:
            fancy_message(request, form.errors, "error")

    queryset = get_user_model().objects.all()

    page = request.GET.get('page')

    items_per_page = 10
    paginator = Paginator(queryset, items_per_page)

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    form = CustomUserCreationForm()
    my_context = {
        "Title": "Account List",
        "users": users,
        "page": page,
        "form": form,
    }

    return render(request, "crm/users/users_list.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def users_detail_view(request, pk, *args, **kwargs):
    user = get_object_or_404(get_user_model(), id=pk)
    form = UserForm(instance=user)
    formset = SeatFormSet(instance=user)
    if request.method == "POST":
        print(request.POST)
        form = UserForm(instance=user, data=request.POST)
        formset = SeatFormSet(instance=user, data=request.POST)
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            fancy_message(request, "Changes saved successfully", level="success")
            return redirect(".")
        else:
            fancy_message(request, form.errors, level="error")
            fancy_message(request, formset.errors, level="error")

    my_context = {
        "Title": user.username,
        "form": form,
        "formset": formset
    }
    return render(request, "crm/users/users_detail.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def orders_list_view(request, *args, **kwargs):
    if request.method == "POST":
        form = OrderForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            fancy_message(request, "Order successfully created!", "success")
            return redirect(".")
        else:
            fancy_message(request, form.errors, "error")
    queryset = Order.objects.all()

    items_per_page = 10

    paginator = Paginator(queryset, items_per_page)

    page = request.GET.get('page')

    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
        orders = paginator.page(1)
    except EmptyPage:
        orders = paginator.page(paginator.num_pages)

    form = OrderForm()

    my_context = {
        "Title": "Order List",
        "orders": orders,
        "page": page,
        "form": form
    }

    return render(request, "crm/orders/orders_list.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def orders_detail_view(request, pk, *args, **kwargs):
    order = get_object_or_404(Order, id=pk)
    my_context = {
        "Title": order.id,
        "order": order,
    }
    return render(request, "crm/orders/orders_detail.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def orders_update_view(request, pk, *args, **kwargs):
    order = get_object_or_404(Order, id=pk)
    form = OrderForm(instance=order)
    formset = OrderItemFormSet(instance=order)
    if request.method == "POST":
        form = OrderForm(instance=order, data=request.POST, files=request.FILES)
        formset = OrderItemFormSet(instance=order, data=request.POST, files=request.FILES)
        if form.is_valid() and formset.is_valid():
            form_obj = form.save()
            formset.save()
            fancy_message(request, "Changes saved successfully", level="success")
            return redirect("crm:orders_detail", pk=form_obj.id)
        else:
            fancy_message(request, form.errors, level="error")
            fancy_message(request, formset.errors, level="error")

    my_context = {
        "Title": "Create Order",
        "form": form,
        "formset": formset
    }
    return render(request, "crm/orders/orders_create.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def orders_create_view(request, *args, **kwargs):
    form = OrderForm()
    formset = OrderItemFormSet()
    if request.method == "POST":
        form = OrderForm(data=request.POST, files=request.FILES)
        formset = OrderItemFormSet(data=request.POST, files=request.FILES)

        if form.is_valid() and formset.is_valid():
            form_obj = form.save()
            formset_obj = formset.save(commit=False)

            for index, item in enumerate(formset_obj):
                item.order = form_obj
                item.save()

                seats = request.POST.getlist(f'order_items-{index}-seats')
                item.seats.set(seats)

            fancy_message(request, "Order successfully created", level="success")
            return redirect("crm:orders_detail", pk=form_obj.id)
        else:
            fancy_message(request, form.errors, level="error")
            fancy_message(request, formset.errors, level="error")

    my_context = {
        "Title": "Create Order",
        "form": form,
        "formset": formset
    }
    return render(request, "crm/orders/orders_create.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def foods_list_view(request, *args, **kwargs):
    if request.method == "POST":
        form = FoodForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            fancy_message(request, "Food successfully created!", "success")
            return redirect(".")
        else:
            fancy_message(request, form.errors, "error")
    queryset = Food.objects.all()

    items_per_page = 10

    paginator = Paginator(queryset, items_per_page)

    page = request.GET.get('page')

    try:
        foods = paginator.page(page)
    except PageNotAnInteger:
        foods = paginator.page(1)
    except EmptyPage:
        foods = paginator.page(paginator.num_pages)

    form = FoodForm()

    my_context = {
        "Title": "Food List",
        "foods": foods,
        "page": page,
        "form": form
    }

    return render(request, "crm/foods/foods_list.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def foods_detail_view(request, pk, *args, **kwargs):
    food = get_object_or_404(Food, id=pk)
    form = FoodForm(instance=food)
    if request.method == "POST":
        form = FoodForm(instance=food, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            fancy_message(request, "Changes saved successfully", level="success")
            return redirect(".")
        else:
            fancy_message(request, form.errors, level="error")

    my_context = {
        "Title": food.name,
        "form": form,
    }
    return render(request, "crm/foods/foods_detail.html", my_context)


@require_POST
@login_required
@user_passes_test(is_manager_user)
def food_delete_view(request, *args, **kwargs):
    id = request.POST.get("food-id")
    food = get_object_or_404(Food, id=id)
    food.delete()
    fancy_message(request, "Food Deleted", level="success")
    return redirect("crm:foods_list")


@login_required
@user_passes_test(is_manager_user)
def categories_list_view(request, *args, **kwargs):
    if request.method == "POST":
        form = CategoryForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            fancy_message(request, "Food successfully created!", "success")
            return redirect(".")
        else:
            fancy_message(request, form.errors, "error")

    queryset = Category.objects.all()

    items_per_page = 10

    paginator = Paginator(queryset, items_per_page)

    page = request.GET.get('page')

    try:
        categories = paginator.page(page)
    except PageNotAnInteger:
        categories = paginator.page(1)
    except EmptyPage:
        categories = paginator.page(paginator.num_pages)

    form = CategoryForm()

    my_context = {
        "Title": "category List",
        "categories": categories,
        "page": page,
        "form": form,
    }

    return render(request, "crm/categories/categories_list.html", my_context)


@login_required
@user_passes_test(is_manager_user)
def categories_detail_view(request, pk, *args, **kwargs):
    category = get_object_or_404(Category, id=pk)
    form = CategoryForm(instance=category)
    if request.method == "POST":
        form = CategoryForm(instance=category, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            fancy_message(request, "Changes saved successfully", level="success")
            return redirect(".")
        else:

backend/templates/crm/extras/extras_detail.html
{% extends 'index.html' %}
{% block content %}
    <form enctype="multipart/form-data" action="." method="post">
        {% csrf_token %}
        <div class="card bg-white shadow-sm border-0">
            <div class="card-body">
                <div class="row row-gap-3">
                    <div class="col-12 col-md-12 ">
                        <div class="form-group w-lg">
                            <label class="form-label" for="{{ form.name.name }}">{{ form.name.label }}</label>
                            {{ form.name }}
                            <small class="text-black-50">{{ form.name.help_text }}</small>
                        </div>
                    </div>
                    <div class="col-12 col-md-12 ">
                        <div class="form-group w-lg">
                            <label class="form-label" for="{{ form.price.name }}">{{ form.price.label }}</label>
                            {{ form.price }}
                            <small class="text-black-50">{{ form.price.help_text }}</small>
                        </div>
                    </div>
                    <div class="col-12 col-md-12 ">
                        <div class="form-group w-lg">
                            <label class="form-label" for="{{ form.is_active.name }}">{{ form.is_active.label }}</label>
                            {{ form.is_active }}
                            <small class="text-black-50">{{ form.is_active.help_text }}</small>
                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="card-footer bg-transparent border-0">
                <button class="btn btn-primary text-white float-end" role="button" type="submit">Save changes</button>
            </div>
        </div>
    </form>
{% endblock %}

backend/templates/crm/extras/extras_list.html
{% extends 'index.html' %}
{% block content %}
    <section>
        <div class="card bg-white border-0 shadow-sm">
            <div class="card-header border-0 bg-transparent">
                <div class="hstack justify-content-between align-items-center">
                    <h2 class="card-title mb-0">Extras</h2>
                    <button class="btn btn-primary text-white" data-bs-toggle="modal" data-bs-target="#modal-extra">
                        Create new extra
                    </button>
                </div>
            </div>
            <div class="card-body table-responsive">
                <table class="table">
                    <thead class="table-dark">
                    <tr>
                        <th scope="row">ID</th>
                        <th scope="row">name</th>
                        <th scope="row">Price</th>
                        <th scope="row" class="text-nowrap">Date Create</th>
                        <th scope="row" class="text-nowrap">Date Modify</th>
                        <th scope="row">Visibility</th>
                        <th scope="row">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for extra in extras %}
                        <tr>
                            <th>#{{ extra.id }}</th>
                            <td>{{ extra.name }}</td>
                            <td>${{ extra.price }}</td>
                            <td class="text-nowrap">{{ extra.create_at }}</td>
                            <td class="text-nowrap">{{ extra.update_at }}</td>
                            <td>
                                {% if extra.is_active %}
                                    <i class="bi bi-check-square-fill text-success"></i>
                                {% else %}
                                    <i class="bi bi-check-square"></i>
                                {% endif %}
                            </td>
                            <td class="text-nowrap">
                                <div class="hstack gap-2">
                                    <a href="{{ extra.get_absolute_url }}" class="btn btn-sm btn-info text-white"><i
                                            class="bi bi-pencil-fill"></i></a>
                                    <button class="btn btn-sm btn-danger text-white btn-extra-delete"
                                            data-id="{{ extra.id }}"
                                            data-name="{{ extra.name }}">
                                        <i class="bi bi-trash3-fill"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="12">No extra have been listed yet</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer border-0 bg-transparent">
                <div class="float-end d-flex align-self-center justify-content-start gap-2">
                    <a href="?page=1" class="btn btn-sm btn-secondary text-white"
                       {% if extras.number == 1 %}disabled {% endif %}>
                        &laquo;First
                    </a>
                    {% if extras.has_previous %}
                        <a href="?page={{ extras.previous_page_number }}" class="btn btn-sm btn-secondary text-white">Previous</a>
                    {% endif %}

                    <span>
                        {{ extras.number }}/{{ extras.paginator.num_pages }}
                    </span>

                    {% if extras.has_next %}
                        <a href="?page={{ extras.next_page_number }}"
                           class="btn btn-sm btn-secondary text-white">Next</a>
                    {% endif %}
                    <a href="?page={{ extras.paginator.num_pages }}" class="btn btn-sm btn-secondary text-white">Last&raquo;</a>
                </div>
            </div>
        </div>
        <div class="modal fade" id="modal-extra" tabindex="-1" aria-labelledby="modalAddExtra" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <form method="post" action="." enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="staticBackdropLabel">Add new extra</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="row row-gap-3">
                                {% for item in form %}
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label class="form-label" for="{{ item.name }}">{{ item.label }}</label>
                                            {{ item }}
                                            <small class="text-black-50">{{ item.help_text }}</small>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary text-white" data-bs-dismiss="modal">Close</button>
                            <button type="submit" role="button" class="btn btn-primary text-white">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modal-extra-delete" tabindex="-1" aria-labelledby="modalDeleteExtra"
             aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <form method="post" action="{% url 'crm:extras_delete' %}" enctype="multipart/form-data">
                        <input type="hidden" name="extra-id" id="input-extra-id" value="">
                        {% csrf_token %}
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="delete-extra-title"></h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body" id="delete-extra-body">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary text-white" data-bs-dismiss="modal">Cancel
                            </button>
                            <button type="submit" role="button" class="btn btn-primary text-white">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}