backend/crm/urls.py
from django.urls import path
from .views import dashboard_view, support_view, users_list_view, users_detail_view, foods_list_view, foods_detail_view, \
    categories_list_view, categories_detail_view, settings_view, settings_theme_view, food_delete_view, \
    category_delete_view, tips_list_view, tips_detail_view, tips_delete_view, extras_list_view, extras_delete_view, \
    extras_detail_view, orders_list_view, orders_detail_view, orders_create_view, orders_update_view
from .api import UserSeatsView

app_name = 'crm'

urlpatterns = [
    path('dashboard/', dashboard_view, name='dashboard'),
    path('dashboard/users/', users_list_view, name='users_list'),
    path('dashboard/users/<int:pk>/', users_detail_view, name='users_detail'),
    path('dashboard/orders/', orders_list_view, name='orders_list'),
    path('dashboard/orders/create/', orders_create_view, name='orders_create'),
    path('dashboard/orders/<int:pk>/update/', orders_update_view, name='orders_update'),
    path('dashboard/orders/<int:pk>/', orders_detail_view, name='orders_detail'),
    path('dashboard/foods/', foods_list_view, name='foods_list'),
    path('dashboard/foods/<int:pk>/', foods_detail_view, name='foods_detail'),
    path('dashboard/foods/delete/', food_delete_view, name='foods_delete'),
    path('dashboard/categories/', categories_list_view, name='categories_list'),
    path('dashboard/categories/<int:pk>/', categories_detail_view, name='categories_detail'),
    path('dashboard/categories/delete/', category_delete_view, name='categories_delete'),
    path('dashboard/tips/', tips_list_view, name='tips_list'),
    path('dashboard/tips/<int:pk>/', tips_detail_view, name='tips_detail'),
    path('dashboard/tips/delete/', tips_delete_view, name='tips_delete'),
    path('dashboard/extras/', extras_list_view, name='extras_list'),
    path('dashboard/extras/<int:pk>/', extras_detail_view, name='extras_detail'),
    path('dashboard/extras/delete/', extras_delete_view, name='extras_delete'),
    path('dashboard/settings/', settings_view, name='dashboard_settings'),
    path('dashboard/settings/theme/', settings_theme_view, name='dashboard_settings_theme'),
    path('dashboard/support/<int:pk>/', support_view, name='dashboard_support'),
    path("api/crm/seats/", UserSeatsView.as_view(), name="seats_list"),
]

backend/checkout/models.py
from django.db import models
from django.db.models import Sum, F
from main.models import Food
from django.contrib.auth import get_user_model
from account.models import Seat
from django.utils.translation import gettext_lazy as _
from decimal import Decimal
from django.shortcuts import reverse
from settings.models import Setting

# Create your models here.


class Extra(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Extra Name"))
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name=_("Extra Price"))
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("Visibility"),
        help_text=_("format: true=visible, false=hidden")
    )
    create_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Date Create"), blank=True, null=True)
    update_at = models.DateTimeField(auto_now=True, verbose_name=_("Date Modified"), blank=True, null=True)

    class Meta:
        verbose_name = _("Extra")
        verbose_name_plural = _("Extras")

    def __str__(self):
        return f"{self.name} - ${self.price}"

    def get_absolute_url(self):
        return reverse("crm:extras_detail", kwargs={"pk": self.pk})


class Tip(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Tip Name"))
    amount = models.DecimalField(max_digits=6, decimal_places=2, verbose_name=_("Tip Amount"))
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("Visibility"),
        help_text=_("format: true=visible, false=hidden")
    )
    create_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Date Create"), blank=True, null=True)
    update_at = models.DateTimeField(auto_now=True, verbose_name=_("Date Modified"), blank=True, null=True)

    class Meta:
        verbose_name = _("Tip")
        verbose_name_plural = _("Tips")

    def __str__(self):
        return f"{self.name} - ${self.amount}"

    def get_absolute_url(self):
        return reverse("crm:tips_detail", kwargs={"pk": self.id})


class Cart(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        verbose_name=_("User"),
        related_name="cart_user",
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        help_text=_("The user who owns the cart.")
    )
    create_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Date Create"))
    update_at = models.DateTimeField(auto_now=True, verbose_name=_("Date Update"))

    class Meta:
        verbose_name = _("Cart")
        verbose_name_plural = _("Carts")
        ordering = ("user",)

    def __str__(self):
        return self.user.get_name()

    def get_items(self):
        items = self.cart_items.all()
        items.filter(food__is_active=False).delete()
        return items

    def get_total_price(self):
        items = self.get_items()
        total_price = 0
        for item in items:
            total_price += item.food.price

        return total_price


class CartItem(models.Model):
    cart = models.ForeignKey(
        Cart,
        verbose_name=_("Cart"),
        on_delete=models.CASCADE,
        related_name="cart_items",
        null=False,
        blank=False,
        help_text=_("The cart this item belongs to.")
    )
    food = models.ForeignKey(
        Food,
        verbose_name=_("Food"),
        on_delete=models.CASCADE,
        related_name="cart_item_food",
        null=False,
        blank=False,
        help_text=_("The food this item belongs to.")
    )
    seats = models.ManyToManyField(
        Seat,
        verbose_name=_("Seat"),
        related_name="cart_item_seats",
        blank=False,
    )
    quantity = models.PositiveIntegerField(default=1, verbose_name=_("Quantity"), help_text=_("The quantity this item"))

    class Meta:
        verbose_name = _("CartItem")
        verbose_name_plural = _("CartItems")
        ordering = ["cart", "-id", "-quantity"]
        unique_together = ("cart", "food")

    def __str__(self):
        return f"{self.quantity} of {self.food}"


class Order(models.Model):
    class PaymentStatusChoices(models.TextChoices):
        PENDING = "PENDING", _("Pending")
        COMPLETED = "COMPLETED", _("Completed")

    class OrderStatusChoices(models.TextChoices):
        PENDING = "PENDING", _("Pending")
        PROCESSING = "PROCESSING", _("Processing")
        COMPLETED = "COMPLETED", _("Completed")

    user = models.ForeignKey(
        get_user_model(),
        verbose_name=_("User"),
        on_delete=models.PROTECT,
        related_name="orders",
        blank=False,
        null=False,
        help_text=_("The user who placed the order.")
    )
    session_id = models.UUIDField(
        verbose_name=_("Session ID"),
        blank=True,
        null=True,
        help_text=_("The session id of the order")
    )
    session_customer = models.CharField(
        verbose_name=_("Session Customer"),
        max_length=255,
        blank=True,
        null=True,
        help_text=_("The session customer of the order")
    )
    extras = models.ManyToManyField(
        Extra,
        verbose_name=_("Extras"),
        blank=True,
        help_text=_("Selected extras for the order.")
    )
    tips = models.ForeignKey(
        Tip,
        verbose_name=_("Tips"),
        blank=True,
        null=True,
        help_text=_("Selected tips for the order."),
        on_delete=models.PROTECT
    )
    payment_method = models.CharField(
        max_length=50,
        verbose_name=_("Payment Method"),
        choices=Setting.PaymentGatewayChoices,
        default=Setting.PaymentGatewayChoices.CASH
    )
    payment_status = models.CharField(
        max_length=50,
        verbose_name=_("Payment Status"),
        choices=PaymentStatusChoices,
        default=PaymentStatusChoices.PENDING
    )
    status = models.CharField(
        max_length=50,
        verbose_name=_("Order Status"),
        choices=OrderStatusChoices,
        default=OrderStatusChoices.PENDING
    )
    description = models.TextField(
        verbose_name=_("Order Description"),
        blank=True,
        null=True,
        help_text=_("Additional notes or description for the order.")
    )
    create_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Order Date"))
    update_at = models.DateTimeField(auto_now=True, verbose_name=_("Last Modified"))

    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")
        ordering = ("-create_at",)

    def __str__(self):
        return f"Order #{self.id} - {self.user.get_name()}"

    def get_total_price(self):
        tip_amount = self.tips.amount if self.tips else 0
        extras_price = self.extras.aggregate(total=Sum("price"))["total"] or 0
        subtotal = self.get_subtotal()
        total_price = tip_amount + extras_price + subtotal
        return total_price

    def get_subtotal(self):
        return self.order_items.values("price", "quantity").aggregate(subtotal=Sum(F("price") * F("quantity")))[
            "subtotal"] or 0

    def get_extras_cost(self):
        return self.extras.values("price").aggregate(total=Sum("price"))["total"] or 0

    def get_absolute_url(self):
        return reverse("crm:orders_detail", kwargs={"pk": self.id})


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        verbose_name=_("Order"),
        related_name="order_items",
        help_text=_("Order items are ordered by this order. ")
    )
    food = models.ForeignKey(
        Food,
        verbose_name=_("Food"),
        on_delete=models.CASCADE,
        related_name="order_item_food",
        null=False,
        blank=False,
        help_text=_("The food this item belongs to.")
    )
    seats = models.ManyToManyField(
        Seat,
        verbose_name=_("Seat"),
        related_name="order_item_seats",
        blank=False,
    )
    quantity = models.PositiveIntegerField(default=1, verbose_name=_("Quantity"), help_text=_("The quantity this item"))
    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name=_("Price"),
        null=True,
        blank=True,
        help_text=_("Cost of the food"),
    )

    class Meta:
        verbose_name = _("OrderItem")
        verbose_name_plural = _("OrderItems")
        ordering = ["order", "-id", "-quantity"]

    def __str__(self):
        return f"{self.quantity} of {self.food}"

    def total_cost(self):
        return (self.price or 0) * self.quantity

backend/crm/models.py
from django.db import models

# Create your models here.

backend/stream/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _


# Create your models here.


class UserRoom(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        verbose_name=_("User"),
        related_name="user_room",
        on_delete=models.CASCADE,
        blank=False,
        null=False
    )
    support = models.ForeignKey(
        get_user_model(),
        verbose_name=_("Support"),
        related_name="user_support",
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    is_active = models.BooleanField(verbose_name=_("Active"), default=False)
    is_busy = models.BooleanField(verbose_name=_("Busy"), default=False)
    update_at = models.DateTimeField(auto_now=True, verbose_name=_("Updated at"))

    class Meta(object):
        verbose_name = _("User Room")
        verbose_name_plural = _("User Rooms")
        ordering = ("-is_active", "-update_at", "-is_busy")

    def __str__(self):
        return self.user.username

backend/templates/crm/orders/orders_create.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

    <form enctype="multipart/form-data" action="." method="post">
        {% csrf_token %}
        <div class="card bg-white shadow-sm border-0">
            <div class="card-body">
                <div class="row row-gap-3">
                    <div class="col-12">
                        <div class="form-group">
                            <label class="form-label" for="{{ form.user.name }}">{{ form.user.label }}</label>
                            <div>
                                {{ form.user }}
                            </div>
                            <small class="text-black-50">{{ form.user.help_text }}</small>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label class="form-label"
                                   for="{{ form.session_customer.name }}">{{ form.session_customer.label }}</label>
                            <div>
                                {{ form.session_customer }}
                            </div>
                            <small class="text-black-50">{{ form.session_customer.help_text }}</small>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label class="form-label"
                                   for="{{ form.description.name }}">{{ form.description.label }}</label>
                            {{ form.description }}
                            <small class="text-black-50">{{ form.description.help_text }}</small>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label class="form-label" for="{{ form.status.name }}">{{ form.status.label }}</label>
                            {{ form.status }}
                            <small class="text-black-50">{{ form.status.help_text }}</small>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label class="form-label"
                                   for="{{ form.payment_status.name }}">{{ form.payment_status.label }}</label>
                            {{ form.payment_status }}
                            <small class="text-black-50">{{ form.payment_status.help_text }}</small>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label class="form-label"
                                   for="{{ form.tips.name }}">{{ form.tips.label }}</label>
                            {{ form.tips }}
                            <small class="text-black-50">{{ form.tips.help_text }}</small>
                        </div>
                    </div>
                    <div class="col-12">
                        <h5 class="fs-5">{{ form.payment_method.label }}</h5>
                        {% for checkbox in form.payment_method %}
                            <div class="form-check form-check-inline">
                                {{ checkbox }}
                                <label class="form-check-label" for="{{ checkbox.name }}">{{ checkbox.label }}</label>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="col-12">
                        <h5 class="fs-5">{{ form.extras.label }}</h5>
                        {% for checkbox in form.extras %}
                            <div class="form-check form-check-inline">
                                {{ checkbox }}
                                <label class="form-check-label" for="{{ checkbox.name }}">{{ checkbox.label }}</label>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <hr/>
                <table class="table " id="formset-container">
                    {{ formset.management_form }}
                    <thead>
                    <tr class="table-dark">
                        <th scope="row">Food</th>
                        <th scope="row">Seat</th>
                        <th scope="row">Quantity</th>
                        <th scope="row">Price</th>
                        <th scope="row">Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in formset %}
                        <tr>
                            {{ item.id }}
                            <td>
                                {{ item.food }}
                            </td>
                            <td>
                                {{ item.seats }}
                            </td>
                            <td>
                                {{ item.quantity }}
                            </td>
                            <td>
                                {{ item.price }}
                            </td>
                            <td>{{ item.DELETE }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr class="table-transparent">
                        <td colspan="12">
                            <button type="button" disabled class="btn btn-sm btn-dark text-white border-0 outline-0"
                                    id="add-form"><i class="bi bi-plus-circle fs-5"></i> Add more item
                            </button>
                        </td>
                    </tr>
                    </tfoot>

                </table>

            </div>
            <div class="card-footer bg-transparent border-0">
                <button class="btn btn-primary text-white float-end" role="button" type="submit">Save changes</button>
            </div>
        </div>
    </form>
    <link rel="stylesheet" href="{% static 'assets/lib/nice-select-2/nice-select2.css' %}">
    <style>
        .nice-select {
            width: 100%;
        }
    </style>
{% endblock %}
{% block script %}
    <script src="{% static 'assets/lib/nice-select-2/nice-select2.js' %}"></script>
    <script type="module">
        import {getData} from "{% static "assets/js/utils.js" %}";

        document.addEventListener('DOMContentLoaded', async function () {
            const userSelectInput = document.querySelector("#id_user")
            const options = {searchable: true,}
            let formCount = parseInt(document.getElementById('id_order_items-TOTAL_FORMS').value);
            let foodOptions = []
            let seatOptions = []
            let NiceSelectFood = {}
            let NiceSelectSeat = {}
            foodOptions = await getData("/api/food-list/")
            if (userSelectInput.value.trim !== "" || userSelectInput.value.length > 0)
                seatOptions = await getData(`/api/crm/seats/?user=${userSelectInput.value}`)

            NiceSelect.bind(document.getElementById(`id_user`), options);
            document.getElementById(`id_user`).classList.add("visually-hidden")


            const handleIterateSelect = (data = null) => {
                for (let i = 1; i <= formCount; i++) {
                    const input_food = document.querySelector(`#id_order_items-${i-1}-food`)
                    const input_seat = document.querySelector(`#id_order_items-${i-1}-seats`)
                    if (!NiceSelectFood[i] && !NiceSelectSeat[i]) {
                        NiceSelectSeat[i] = NiceSelect.bind(input_seat, options);
                        NiceSelectFood[i] = NiceSelect.bind(input_food, options);
                        input_food.classList.add("visually-hidden")
                        input_seat.classList.add("visually-hidden")
                    }
                    if (data) {
                        input_seat.innerHTML = ``
                        input_seat.innerHTML = `${data?.map(seat => `<option value="${seat?.id}">${seat?.name}</option>`)}`
                        NiceSelectSeat[i].update()
                        NiceSelectSeat[i].dropdown.classList.remove("visually-hidden")
                    }

                }
            }
            handleIterateSelect()


            const handleValidateAddSeat = (value) => {
                const btn = document.querySelector("#add-form")
                if (value.trim === "" || value.length === 0 || value === null || value === undefined) {
                    btn.setAttribute("disabled", true)
                } else {
                    btn.removeAttribute("disabled")
                }
            }

            handleValidateAddSeat(userSelectInput.value)

            window.removeRow = (e) => {
                const btn = e.currentTarget
                btn.parentNode.parentNode.remove()
                document.getElementById('id_order_items-TOTAL_FORMS').value -= 1;
                formCount = parseInt(document.getElementById('id_order_items-TOTAL_FORMS').value);
            }


            userSelectInput.addEventListener("change", async (e) => {
                const id = e.currentTarget.value
                handleValidateAddSeat(id)
                seatOptions = await getData(`/api/crm/seats/?user=${id}`)

                handleIterateSelect(seatOptions)


            })

            document.getElementById('add-form').addEventListener('click', function () {

                const table = document.querySelector("#formset-container")
                const length = table.querySelectorAll("tbody tr").length
                const row = table.insertRow(length + 1)
                row.innerHTML = `
                <tr>
                            <input type="hidden" name="order_items-${formCount}-id" id="id_order_items-${formCount}-id">
                            <td>
                                <select name="order_items-${formCount}-food" aria-describedby="id_order_items-${formCount}-food_helptext" id="id_order_items-${formCount}-food">
                                  <option value="" selected="">---------</option>
                                   ${foodOptions?.map(food => `<option value="${food?.id}">${food?.name}</option>`)}
                                </select>
                            </td>
                            <td>
                                <select name="order_items-${formCount}-seats" multiple id="id_order_items-${formCount}-seats">
                                    ${seatOptions?.map(seat => `<option value="${seat?.id}">${seat?.name}</option>`)}
                                </select>
                            </td>
                            <td>
                                <input type="number" name="order_items-${formCount}-quantity" value="1" class="form-control" placeholder="Quantity" min="0" aria-describedby="id_order_items-${formCount}-quantity_helptext" id="id_order_items-${formCount}-quantity">
                          
                            </td>
                            <td>
                                <input type="number" name="order_items-${formCount}-price" class="form-control" placeholder="Price of Food" step="0.01" aria-describedby="id_order_items-${formCount}-price_helptext" id="id_order_items-${formCount}-price">
                            </td>
                            <td>
                                <button class="btn border-0 outline-0" onclick="removeRow(event)" role="button" type="button">
                                    <i class="bi bi-x-circle-fill"></i>
                                </button>
                            </td>
                        </tr>
                `

                const selectSeat = NiceSelect.bind(document.getElementById(`id_order_items-${formCount}-seats`), options);
                const selectFood = NiceSelect.bind(document.getElementById(`id_order_items-${formCount}-food`), options);
                NiceSelectSeat[formCount+1] = selectSeat
                NiceSelectFood[formCount+1] = selectFood
                console.log(NiceSelectSeat)
                document.getElementById(`id_order_items-${formCount}-seats`).classList.add("visually-hidden")
                document.getElementById(`id_order_items-${formCount}-food`).classList.add("visually-hidden")

                document.getElementById('id_order_items-TOTAL_FORMS').value = formCount + 1;
                formCount = parseInt(document.getElementById('id_order_items-TOTAL_FORMS').value);

            });
        });
    </script>
{% endblock %}

backend/templates/crm/orders/orders_list.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <section>
        <div class="card bg-white border-0 shadow-sm">
            <div class="card-header border-0 bg-transparent">
                <div class="hstack justify-content-between align-items-center">
                    <h2 class="card-title mb-0">Orders</h2>
                    <a href="{% url "crm:orders_create" %}" class="btn btn-primary text-white">
                        Create new order
                    </a>
                </div>
            </div>
            <div class="card-body table-responsive">
                <table class="table">
                    <thead class="table-dark">
                    <tr>
                        <th scope="row">ID</th>
                        <th scope="row">Table</th>
                        <th scope="row">Alias</th>
                        <th scope="row">Status</th>
                        <th scope="row">Method</th>
                        <th scope="row">Payment</th>
                        <th scope="row" class="text-nowrap">Date Create</th>
                        <th scope="row" class="text-nowrap">Date Modify</th>
                        <th scope="row">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr>
                            <th>#{{ order.pk }}</th>
                            <td>{{ order.user }}</td>
                            <td>{{ order.session_customer }}</td>
                            <td>{{ order.get_status_display }}</td>
                            <td>{{ order.get_payment_method_display }}</td>
                            <td>{{ order.get_payment_status_display }}</td>
                            <td class="text-nowrap">{{ order.create_at }}</td>
                            <td class="text-nowrap">{{ order.update_at }}</td>
                            <td class="text-nowrap">
                                <div class="hstack gap-2">
                                    <a href="{{ order.get_absolute_url }}" class="btn btn-sm btn-primary text-white"><i
                                            class="bi bi-eye-fill"></i></a>
                                    <a href="{% url "crm:orders_update" order.id %}" class="btn btn-sm btn-info text-white"><i
                                            class="bi bi-pencil-fill"></i></a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer border-0 bg-transparent">
                <div class="float-end d-flex align-self-center justify-content-start gap-2">
                    <a href="?page=1" class="btn btn-sm btn-secondary text-white"
                       {% if foods.number == 1 %}disabled {% endif %}>&laquo;
                        First</a>
                    {% if foods.has_previous %}
                        <a href="?page={{ foods.previous_page_number }}" class="btn btn-sm btn-secondary text-white">Previous</a>
                    {% endif %}

                    <span>
                        {{ foods.number }}/{{ foods.paginator.num_pages }}
                    </span>

                    {% if foods.has_next %}
                        <a href="?page={{ foods.next_page_number }}"
                           class="btn btn-sm btn-secondary text-white">Next</a>
                    {% endif %}
                    <a href="?page={{ foods.paginator.num_pages }}" class="btn btn-sm btn-secondary text-white">Last
                        &raquo;</a>
                </div>
            </div>
        </div>
        <div class="modal fade" id="modal-food" tabindex="-1" aria-labelledby="modalAddFood" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <form method="post" action="." enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="staticBackdropLabel">Add new food</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="row row-gap-3">
                                {% for item in form %}
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label class="form-label" for="{{ item.name }}">{{ item.label }}</label>
                                            {{ item }}
                                            <small class="text-black-50">{{ item.help_text }}</small>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary text-white" data-bs-dismiss="modal">Close
                            </button>
                            <button type="submit" role="button" class="btn btn-primary text-white">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modal-food-delete" tabindex="-1" aria-labelledby="modalDeleteFood"
             aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <form method="post" action="{% url 'crm:foods_delete' %}" enctype="multipart/form-data">
                        <input type="hidden" name="food-id" id="input-food-id" value="">
                        {% csrf_token %}
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="delete-food-title"></h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body" id="delete-food-body">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary text-white" data-bs-dismiss="modal">Cancel
                            </button>
                            <button type="submit" role="button" class="btn btn-primary text-white">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}