backend/account/urls.py
from django.urls import path
from .views import login_view,logout_view
from .api import UserDetail

app_name = 'account'

urlpatterns = [
    path("auth/login/", login_view, name="login"),
    path("auth/logout/", logout_view, name="logout"),
    path("api/user/", UserDetail.as_view(), name="user_detail")
]

backend/crm/urls.py
from django.urls import path
from .views import dashboard_view, support_view, users_list_view, users_detail_view, foods_list_view, foods_detail_view, \
    categories_list_view, categories_detail_view, settings_view, settings_theme_view, food_delete_view, \
    category_delete_view, tips_list_view, tips_detail_view, tips_delete_view, extras_list_view, extras_delete_view, \
    extras_detail_view, orders_list_view, orders_detail_view, orders_create_view, orders_update_view
from .api import UserSeatsView

app_name = 'crm'

urlpatterns = [
    path('dashboard/', dashboard_view, name='dashboard'),
    path('dashboard/users/', users_list_view, name='users_list'),
    path('dashboard/users/<int:pk>/', users_detail_view, name='users_detail'),
    path('dashboard/orders/', orders_list_view, name='orders_list'),
    path('dashboard/orders/create/', orders_create_view, name='orders_create'),
    path('dashboard/orders/<int:pk>/update/', orders_update_view, name='orders_update'),
    path('dashboard/orders/<int:pk>/', orders_detail_view, name='orders_detail'),
    path('dashboard/foods/', foods_list_view, name='foods_list'),
    path('dashboard/foods/<int:pk>/', foods_detail_view, name='foods_detail'),
    path('dashboard/foods/delete/', food_delete_view, name='foods_delete'),
    path('dashboard/categories/', categories_list_view, name='categories_list'),
    path('dashboard/categories/<int:pk>/', categories_detail_view, name='categories_detail'),
    path('dashboard/categories/delete/', category_delete_view, name='categories_delete'),
    path('dashboard/tips/', tips_list_view, name='tips_list'),
    path('dashboard/tips/<int:pk>/', tips_detail_view, name='tips_detail'),
    path('dashboard/tips/delete/', tips_delete_view, name='tips_delete'),
    path('dashboard/extras/', extras_list_view, name='extras_list'),
    path('dashboard/extras/<int:pk>/', extras_detail_view, name='extras_detail'),
    path('dashboard/extras/delete/', extras_delete_view, name='extras_delete'),
    path('dashboard/settings/', settings_view, name='dashboard_settings'),
    path('dashboard/settings/theme/', settings_theme_view, name='dashboard_settings_theme'),
    path('dashboard/support/<int:pk>/', support_view, name='dashboard_support'),
    path("api/crm/seats/", UserSeatsView.as_view(), name="seats_list"),
]

backend/main/urls.py
from django.urls import path
from .views import home_view, support_view, settings_view,order_list_view
from .api import FoodDetail, FoodList, CategoryList

app_name = 'main'

urlpatterns = [
    path("", home_view, name="home"),
    path("order-list/", order_list_view, name="order_list"),
    path("support/", support_view, name="support"),
    path("settings/", settings_view, name="settings"),
    path("api/food-detail/<int:id>/", FoodDetail.as_view(), name="food_detail"),
    path("api/food-list/", FoodList.as_view(), name="food_list"),
    path("api/category-list/", CategoryList.as_view(), name="category_list"),
]

backend/main/models.py
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.utils.translation import gettext_lazy as _
from autoslug import AutoSlugField
from django.utils import timezone
from django.core.validators import MinValueValidator
from decimal import Decimal
from django.shortcuts import reverse


def category_image(instance, filename):
    timestamp = timezone.now().strftime('%Y%m%d_%H%M%S')
    extension = filename.split('.')[-1]
    return f'images/category/{timestamp}.{extension}'


def food_image(instance, filename):
    timestamp = timezone.now().strftime('%Y%m%d_%H%M%S')
    extension = filename.split('.')[-1]
    return f'images/food/{timestamp}.{extension}'


class Category(models.Model):
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=255,
        unique=True,
        null=False,
        blank=False,
        help_text=_("format: max-255, required")
    )
    slug = AutoSlugField(
        populate_from="name",
        blank=True,
        null=True,
        help_text=_("format: automatically created")
    )
    description = models.TextField(
        verbose_name=_("Description"),
        blank=True,
        null=True,
        help_text=_("Additional details about the category")
    )
    image = models.ImageField(
        verbose_name=_("Image"),
        upload_to=category_image,
        null=True,
        blank=True,
        help_text=_("Category image")
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("Visibility"),
        help_text=_("format: true=visible, false=hidden")
    )
    create_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Date Create"), blank=True, null=True)
    update_at = models.DateTimeField(auto_now=True, verbose_name=_("Date Modified"), blank=True, null=True)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        ordering = ("-id",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("crm:categories_detail", kwargs={"pk": self.id})


class Food(models.Model):
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=255,
        unique=True,
        null=False,
        blank=False,
        help_text=_("format: max-255, required")
    )
    slug = AutoSlugField(
        populate_from="name",
        blank=True,
        null=True,
        help_text=_("format: automatically created")
    )
    description = models.TextField(
        verbose_name=_("Description"),
        blank=True,
        null=True,
        help_text=_("Additional details about the food")
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="food_category",
        verbose_name=_("Category"),
        help_text=_("Food Category")
    )
    thumbnail = models.ImageField(
        verbose_name=_("Image"),
        upload_to=food_image,
        null=True,
        blank=True,
        help_text=_("Food thumbnail image")
    )
    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name=_("Price"),
        null=True,
        blank=True,
        help_text=_("Cost of the food"),
        validators=[
            MinValueValidator(Decimal(0.00))
        ]
    )
    ingredients = models.TextField(
        verbose_name=_("Ingredients"),
        blank=True,
        null=True,
        help_text=_("List of ingredients used in the food")
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("Visibility"),
        help_text=_("format: true=visible, false=hidden")
    )
    create_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Date Create"), blank=True, null=True)
    update_at = models.DateTimeField(auto_now=True, verbose_name=_("Date Modified"), blank=True, null=True)

    class Meta:
        verbose_name = _("Food")
        verbose_name_plural = _("Foods")
        ordering = ("-id",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("crm:foods_detail", kwargs={"pk": self.id})

backend/main/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from account.models import Seat


class CustomerForm(forms.ModelForm):
    first_name = forms.CharField(
        label=_("Full Name"),
        max_length=50,
        help_text=_("example : john doe"),
        widget=forms.TextInput(attrs={'class': "form-control", "id": "full_name"})
    )

    class Meta:
        model = get_user_model()
        fields = ['first_name']


class SeatForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput())
    seat_number = forms.IntegerField(
        required=False,
        disabled=True,
        label=_("Seat Number"),
        min_value=0,
        widget=forms.TextInput(attrs={'class': 'form-control', "readonly": True})
    )
    seat_name = forms.CharField(
        max_length=50,
        required=False,
        label=_("Seat Name"),
        help_text=_("name of the person who seat on that chair"),
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Seat
        fields = ["id", "seat_number", "seat_name"]
        read_only_fields = ["id", "seat_number"]


SeatFormSet = forms.modelformset_factory(Seat, form=SeatForm, extra=0)

backend/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Category, Food
from .forms import CustomerForm, SeatFormSet
from checkout.models import Order
from account.models import Seat
from core.utils import fancy_message
from account.utils import get_current_session, is_table_user


# Create your views here.

@login_required
@user_passes_test(is_table_user, login_url="crm:dashboard")
def home_view(request, *args, **kwargs):
    sessions = request.user.session_set.all().first()

    # print(sessions.get_decoded())

    my_context = {
        "Title": "Home",
    }
    return render(request, "main/home.html", my_context)


@login_required
@user_passes_test(is_table_user, login_url="crm:dashboard")
def order_list_view(request, *args, **kwargs):
    my_context = {
        "Title": "Order List",
    }
    return render(request, "main/order_list.html", my_context)


@login_required
@user_passes_test(is_table_user, login_url="crm:dashboard")
def support_view(request, *args, **kwargs):
    my_context = {
        "Title": "Support"
    }
    return render(request, "stream/call.html", my_context)


@login_required
@user_passes_test(is_table_user, login_url="crm:dashboard")
def settings_view(request, *args, **kwargs):
    customer_form = CustomerForm(instance=request.user)
    seat_form_set = SeatFormSet(queryset=Seat.objects.filter(user=request.user))

    if request.method == "POST":
        customer_form = CustomerForm(instance=request.user, data=request.POST)
        seat_form_set = SeatFormSet(queryset=Seat.objects.filter(user=request.user), data=request.POST)

        if customer_form.is_valid() and seat_form_set.is_valid():
            customer_obj = customer_form.save()
            seat_form_set.save()
            request.session['customer'] = customer_obj.get_name()
            fancy_message(request, "New settings have been saved.", "success")
            return redirect('main:settings')
        else:
            fancy_message(request, "There was an error saving your settings. Please check the form.", "error")

    my_context = {
        "Title": "Settings",
        "customer_form": customer_form,
        "formset": seat_form_set
    }
    return render(request, "main/settings.html", my_context)

backend/templates/loader.html
<div class="d-flex justify-content-center align-items-center my-2 gap-2">
    <div class="spinner-grow text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
</div>

backend/templates/main.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <label for="username" id="username-label" class="form-label">Username</label>
        <input id="username" class="form-control " type="text" name="username"/>
        <button id="btn-join" class="btn btn-primary my-2">Join room</button>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-md-2">
            <div class="col">
                <div class="row row-cols-2 g-2" id="video-container">
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <video id="local-video" autoplay playsinline class="card-img">
                                </video>
                            </div>
                            <div class="card-footer">
                                <button id="btn-toggle-audio">
                                    Audio Mute
                                </button>
                                <button id="btn-toggle-video">
                                    Video Off
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <h3>Chat</h3>
                <div id="messages">
                    <ul id="message-list">

                    </ul>
                </div>
                <div>
                    <input id="message-input" type="text" class="form-control"/>
                    <button class="btn btn-primary my-2" id="btn-send-message">Send Message</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'assets/js/webrtc.js' %}" type="text/javascript"></script>
{% endblock %}

backend/templates/sidebar.html
{% load custom_filters %}
{% url 'main:home' as home %}
{% url 'account:logout' as logout %}
{% url 'main:order_list' as order_list %}
{% url 'main:support' as support %}
{% url 'main:settings' as user_settings %}
{% url 'crm:dashboard' as dashboard %}
{% url 'crm:users_list' as users_list %}
{% url 'crm:orders_list' as orders_list %}
{% url 'crm:foods_list' as foods_list %}
{% url 'crm:categories_list' as categories_list %}
{% url 'crm:tips_list' as tips_list %}
{% url 'crm:extras_list' as extras_list %}
{% url 'crm:dashboard_settings' as dashboard_settings %}

<aside id="sidebar-aside">
    <div class="sidebar-wrapper shadow">
        <div class="sidebar">
            <div class="d-flex justify-content-center align-items-center text-center">
                {% if setting %}
                    {% if setting.logo_mini %}
                        <img src="{{ setting.logo_mini.url }}" alt="{{ setting.company_name }}" class="card-img" width="64"
                             height="64"/>
                    {% else %}
                        <h5 class="card-title text-primary fw-bold">{{ setting.company_name }}</h5>
                    {% endif %}
                {% else %}
                    <h5 class="card-title text-primary fw-bold">Logo</h5>
                {% endif %}
            </div>
            <hr/>
            <ul class="list-unstyled">
                {% if request.user|has_group:'Table' %}
                    <li class="my-3 {% if request.path == home %}bg-primary-subtle{% endif %} rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == home %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ home }}">
                            <i class="bi bi-house fs-1"></i>
                            <small class="my-0">Home</small>
                        </a>
                    </li>
                    <li class="my-3 {% if request.path == order_list %}bg-primary-subtle{% endif %} rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == order_list %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ order_list }}">
                            <i class="bi bi-clipboard fs-1"></i>
                            <small class="my-0">Orders</small>
                        </a>
                    </li>
                    <li class="my-3 {% if request.path == support %}bg-primary-subtle{% endif %} rounded  nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == support %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ support }}">
                            <i class="bi bi-headset fs-1"></i>
                            <small class="my-0">Support</small>
                        </a>
                    </li>
                    <li class="my-3 {% if request.path == user_settings %}bg-primary-subtle{% endif %} rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == user_settings %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ user_settings }}">
                            <i class="bi bi-gear fs-1"></i>
                            <small class="my-0">Settings</small>
                        </a>
                    </li>
                {% elif request.user|has_group:'Manager' %}
                    <li class="my-3 {% if request.path == dashboard %}bg-primary-subtle{% endif %} rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == dashboard %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ dashboard }}">
                            <i class="bi bi-app fs-1"></i>
                            <small class="my-0 text-truncate">Dashboard</small>
                        </a>
                    </li>
                    <li class="my-3 {% if request.path == users_list or "users" in request.path %}bg-primary-subtle{% endif %} rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == users_list or "users" in request.path %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ users_list }}">
                            <i class="bi bi-people fs-1"></i>
                            <small class="my-0 text-truncate">Users</small>
                        </a>
                    </li>
                    <li class="my-3 {% if request.path == orders_list or "orders" in request.path %}bg-primary-subtle{% endif %} rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == orders_list or "orders" in request.path %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ orders_list }}">
                            <i class="bi bi-clipboard fs-1"></i>
                            <small class="my-0 text-truncate">Orders</small>
                        </a>
                    </li>
                    <li class="my-3 {% if request.path == foods_list or "foods" in request.path %}bg-primary-subtle{% endif %} rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == foods_list  or "foods" in request.path %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ foods_list }}">
                            <i class="bi bi-egg-fried fs-1"></i>
                            <small class="my-0 text-truncate">Foods</small>
                        </a>
                    </li>
                    <li class="my-3 {% if request.path == categories_list  or "categories" in request.path %}bg-primary-subtle{% endif %} rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == categories_list or "categories" in request.path %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ categories_list }}">
                            <i class="bi bi-grid fs-1"></i>
                            <small class="my-0 text-truncate">Categories</small>
                        </a>
                    </li>
                    <li class="my-3 {% if request.path == extras_list or "extras" in request.path %}bg-primary-subtle{% endif %} rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == extras_list or "extras" in request.path %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ extras_list }}">
                            <i class="bi bi-bag-plus fs-1"></i>
                            <small class="my-0 text-truncate">Extras</small>
                        </a>
                    </li>
                    <li class="my-3 {% if request.path == tips_list or "tips" in request.path %}bg-primary-subtle{% endif %} rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == tips_list or "tips" in request.path  %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ tips_list }}">
                            <i class="bi bi-cash-coin fs-1"></i>
                            <small class="my-0 text-truncate">Tips</small>
                        </a>
                    </li>
                    <li class="my-3 {% if request.path == users_list %}bg-primary-subtle{% endif %} rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == users_list %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ users_list }}">
                            <i class="bi bi-bar-chart fs-1"></i>
                            <small class="my-0 text-truncate">Analytics</small>
                        </a>
                    </li>
                    <li class="my-3 {% if request.path == dashboard_settings or "settings" in request.path  %}bg-primary-subtle{% endif %} rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 {% if request.path == dashboard_settings or "settings" in request.path %}link-primary {% else %}link-dark{% endif %} "
                           href="{{ dashboard_settings }}">
                            <i class="bi bi-gear fs-1"></i>
                            <small class="my-0 text-truncate">Settings</small>
                        </a>
                    </li>
                    <li class="my-3 rounded nav-item">
                        <a class="nav-link  d-flex flex-row flex-md-column align-items-center justify-content-start gap-2 pb-md-2 gap-md-0 link-dark "
                           href="{{ logout }}">
                            <i class="bi bi-box-arrow-right fs-1"></i>
                            <small class="my-0 text-truncate">Logout</small>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</aside>